# BUILD IMAGE
FROM adoptopenjdk/openjdk13:alpine AS build

ARG APP_VERSION=1.0-SNAPSHOT

WORKDIR /build 

COPY .mvn ./.mvn
COPY . ./

RUN ./mvnw package -pl helloworld

# RUNTIME IMAGE
FROM adoptopenjdk/openjdk13:alpine-jre

ARG APP_VERSION=1.0

WORKDIR /app
COPY --from=build /build/helloworld/target/helloworld-1.0-SNAPSHOT.jar app.jar

EXPOSE 8080
CMD ["java", "-jar", "/app/app.jar"]
