# BUILD TIME
FROM oracle/graalvm-ce:20.0.0-java11

WORKDIR /app

# Copy app
COPY target/simple-web-app-1.0-SNAPSHOT.jar .

# Build native binary
RUN gu install native-image
RUN native-image --no-server --static -cp simple-web-app-1.0-SNAPSHOT.jar com.example.App basicwebapp

#
#
#
#
# RUNTIME
FROM scratch

EXPOSE 8080

COPY --from=0 /app/basicwebapp .
CMD ["./basicwebapp"]
